; Source: Madeena-software/deploy-templates/templates/prod/standard-php.ini
; @ 569a30d4a089b0ee404ed6e963fdd2dfd96d3787
[PHP]
expose_php = Off
memory_limit = 256M
max_execution_time = 300
max_input_time = 300
max_input_vars = 5000
upload_max_filesize = 100M
post_max_size = 201M

[opcache]
opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 0
